{
    showSplashScren: {
        type: 'bool',
        value: false,
        description: 'Show splash screen'
    },
    frame: {
        type: 'bool',
        value: true,
        description: 'Show window caption'
    },
    test: {
        type: 'string',
        value: 'Some content',
        description: 'Test field'
    },    
}