showSplashScren:
  type: bool
  value: true
  description: Show splash screen
frame:
  type: bool
  value: false
  description: Show window caption
test:
  type: string
  value: Some contentQRFDEWR
  description: Test field
