showSplashScren: {type: bool, description: Show splash screen, value: false}
frame: {type: bool, description: Show window caption, value: false}
test: {type: string, description: Test field, value: Some contentQRFDEWR}
hideTaggerAfterSetTag: {type: bool, description: Hide tagger after set tag, value: true}
